databases:
  - name: restaurant-db
    plan: free
    databaseName: restaurant_db_ggh2
    user: restaurant_db_ggh2_user

services:
  - type: web
    plan: free
    region: frankfurt
    name: restaurant-manager
    runtime: python
    buildCommand: "./restaurantApp/build.sh"
    startCommand: "python -m gunicorn restaurantAPP.restaurantApp.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db
          property: connectionString
      - key: PORT
        value: 1000
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
