tadatabases:
  - name: restaurant-db
    plan: free
    databaseName: restaurant_db_ggh2
    user: restaurant_db_ggh2_user

services:
  - type: web
    plan: free
    name: restaurant_db_ggh2_user
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn restaurantApp.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant_db_ggh2
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
