# Generated by Django 4.2.11 on 2024-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('l', 'litre'), ('kg', 'kilogramm'), ('bottle', 'bottle'), ('eggs', 'eggs')], max_length=10),
        ),
    ]
