# Generated by Django 4.2.11 on 2024-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0002_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipereq',
            name='unit',
            field=models.CharField(choices=[('tbs', 'table spoon'), ('ml', 'mililitres'), ('g', 'grams'), ('eggs', 'eggs')], default='-', max_length=10),
        ),
    ]
