# Generated by Django 4.2.11 on 2024-05-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0004_purchase_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bill_nr',
            field=models.IntegerField(default=0),
        ),
    ]
