# Generated by Django 4.2.11 on 2024-05-13 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0008_alter_purchase_bill_nr_alter_purchase_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
