# Generated by Django 4.2.11 on 2024-06-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0009_alter_purchase_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='recipereq',
            name='unit',
            field=models.CharField(choices=[('tbs', 'table spoon'), ('ml', 'mililitres'), ('g', 'grams'), ('eggs', 'eggs'), ('bottle', 'bottle')], default='-', max_length=10),
        ),
    ]
