# Generated by Django 4.2.11 on 2024-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantManager', '0012_menuitem_cost_alter_ingredient_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='recipereq',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
